name: Framework Pull Request
on:
  push:
    tags:
      - "*"
    # Below for testing only
    branches:
      - cahir.autoFWPR
jobs:
  framework-pull-request:
    name: Create FW PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch tag
        uses: actions/checkout@v3
      - name: Set Core version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout FW
        uses: actions/checkout@v3
        with:
          path: "fw"
          ref: "master"
          repository: "adaptlearning/adapt_framework"
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
          persist-credentials: true
      - name: Make changes to .gitmodules
        shell: bash
        run: |
          echo "[submodule "src/core"]
            path = src/core
            branch = master
            url = https://github.com/adaptlearning/adapt-contrib-core
            installBranch = ${{ env.RELEASE_VERSION }}" > .gitmodules
      - name: Commit to new branch
        working-directory: "fw"
        run: |
          git add .
          git checkout -b core-bump-${{ env.RELEASE_VERSION }}
          git status
          git config --global user.name "Github Action Commit"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git commit -m "Fix: Bumping core version automatically via 'frameworkpullrequest' Github action"
          git push --set-upstream origin core-bump-${{ env.RELEASE_VERSION }}

        # uses: devops-infra/action-commit-push@master
        # with:
        #   github_token: "${{ secrets.GITHUB_TOKEN }}"
        #   add_timestamp: true
        #   commit_prefix: "Fix: "
        #   commit_message: "Bumping core version automatically via 'frameworkpullrequest' Github action"
        #   force: false
        #   target_branch: "core-bump-${{ env.RELEASE_VERSION }}"
      # - name: Create" PR
      #   uses: peter-"evans/create-pull-request@v4
