name: Framework Pull Request
on:
  push:
    tags:
      - '*'
    # Below for testing only
    branches:
     - cahir.autoFWPR
jobs:
  framework-pull-request:
    name: Create FW PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch tag
        uses: actions/checkout@v3
      - name: Set Core version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      # "Test" step to be deleted
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          echo "Core version = ${{ env.RELEASE_VERSION }}"
          echo ${{ env }}
      # - name: Make changes to .gitmodules
      #   run: |
      #     git add .gitmodules
      #     git commit -m "Core version bump"
        # uses: actions/setup-node@v3
        # with:
        #   node-version: 'lts/*'
      - name: Commit to new branch
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: true
          commit_prefix: "Fix: "
          commit_message: "Bumping core version automatically via 'frameworkpullrequest' Github action"
          force: false
          target_branch: "core-bump-${{ env.RELEASE_VERSION }}"
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
