name: Create AdaptFramework Pull Request
on:
  push:
    tags:
      - "*"
    # Below for testing only
    branches:
      - cahir.autoFWPR
jobs:
  framework-pull-request:
    name: Create FW PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch tag
        uses: actions/checkout@v3
      - name: Set Core version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout FW
        uses: actions/checkout@v3
        with:
          path: "fw"
          ref: "master"
          repository: "adaptlearning/adapt_framework"
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
          persist-credentials: true
      - name: Make changes to .gitmodules
        shell: bash
        working-directory: "fw"
        run: |
          cat .gitmodules
          echo -e "[submodule "src/core"]
          \tpath = src/core
          \tbranch = master
          \turl = https://github.com/adaptlearning/adapt-contrib-core
          \tinstallBranch = ${{ env.RELEASE_VERSION }}" >> .gitmodules
          cat .gitmodules
      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        with:
          path: "fw"
          branch: core-bump-${{ env.RELEASE_VERSION }}
          commit-message: "Fix: Bumping core version automatically via 'frameworkpullrequest' Github action"
