name: Create AdaptFramework Pull Request
on:
  push:
    tags:
      - "*"
    # Below for testing only
    branches:
      - cahir.autoFWPR
jobs:
  framework-pull-request:
    name: Create FW PR
    runs-on: ubuntu-latest
    steps:
      - name: Fetch tag
        uses: actions/checkout@v3
      - name: Set Core version
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo pwd
      - name: Checkout FW
        uses: actions/checkout@v3
        with:
          path: "fw"
          ref: "master"
          repository: "adaptlearning/adapt_framework"
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0
          persist-credentials: true
      - name: Make changes to .gitmodules
        shell: bash
        working-directory: "fw"
        run: |
          echo pwd
          echo "[submodule "src/core"]
            path = src/core
            branch = master
            url = https://github.com/adaptlearning/adapt-contrib-core
            installBranch = ${{ env.RELEASE_VERSION }}" > .gitmodules
      - name: Create test file
        run: date +%s > test.txt
      - name: Commit to new branch
        shell: bash
        working-directory: "fw"
        run: |
          echo pwd
          cat .gitmodules
          ls
          cat .gitconfig
          git config --global user.name "Github Commit"
          git config --global user.email "secrets.BOT_EMAIL@needed.com"
          git checkout -b core-bump-${{ env.RELEASE_VERSION }}
          git add .
          git status
          git commit -m "Fix: Bumping core version automatically via 'frameworkpullrequest' Github action"
          git push --set-upstream origin core-bump-${{ env.RELEASE_VERSION }}
      # - name: Create" PR
      #   uses: peter-"evans/create-pull-request@v4
